language: haxe
dist: xenial
haxe:
 - development

install:
 - haxelib install hxnodejs
 - haxelib git vscode-json-rpc https://github.com/vshaxe/vscode-json-rpc
 - haxelib git dox https://github.com/HaxeFoundation/dox

script:
 - haxe build.hxml
 - haxe doc.hxml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  on:
    branch: master
