name: CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npx haxe build.hxml
    - name: Build Docs
      run: |
        npx lix install gh:HaxeFoundation/dox
        npx haxe doc.hxml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: out
      if: github.ref == 'refs/heads/master'
